### ISSUE TITLE
Postgres database client- wanted

### ISSUE THREAD

**Issue by jamsheer-thottathil** [otissv/create-graphql-guru#1]
I am getting error while trying to install postgres library, It seems like library is not available in repository.

I tried  `npm install graphql-guru-postgres`  to install library

**Comment by otissv** [comment]
HI, that's because graphql-guru-postgres library does not exist. 

Guru can support any database inside its resolvers and database client/library is a resolver with predefined methods.

Currently, I have only written libraries for MongoDB, RethinkDB and Redis which all have the same basic generic methods names.  I don't actually know Postgres, though. As there are many databases out there, I am hoping the community will chip in and create these for all to uses. But creating a database client is not difficult as it is a wrapper around already existing database clients for nodejs.

Maybe this is something you could help with?

I plan on releasing a tutorial soon regarding how to create a database client. In the mean time, I will post a gist with the skeleton of the module.

**Comment by otissv** [comment]
Here a template that I used for the other clients https://gist.github.com/otissv/0af4ec095cad292a4294bd7f76bc9dce

**Comment by otissv** [comment]
I had a look at sequelize. Never used it before but got it working with sqlite. But I only did findAll method. When I get some time I'll do the other methods too. Also, I added auto-generating models. These are just generic types, but good enough for testing 

```
Import Sequelize from 'sequelize';
import autobind from 'class-autobind';

export function promise (fn) {
  return new Promise((resolve, reject) => fn(resolve, reject));
}

function Model ({ db, fields, table }) {
  const types = {
    array: Sequelize.ARRAY(Sequelize.TEXT),
    boolean: Sequelize.BOOLEAN,
    number: Sequelize.FLOAT,
    string: Sequelize.STRING
  };

  const Model = db.define(
    table,
    Object.keys(fields).reduce((previous, field) => {
      const current = fields[field];

      return {
        ...previous,
        [field]: {
          type: types[current.type],
          allowNull: !current.required
        }
      };
    })
  );

  return Promise.resolve(Model);
}

export function connect ({
  username,
  databases,
  port,
  dialect,
  host,
  pool,
  storage
}) {
  const db = new Sequelize('database', 'username', 'password', {
    host,
    dialect,
    pool,
    storage
  });

  db
    .authenticate()
    .then(() => {
      console.log('Connection has been established successfully.');
    })
    .catch(err => {
      console.error('Unable to connect to the database:', err);
    });

  return db;
}

export class SequelizeQuery {
  constructor () {
    autobind(this);
  }

  resolve (params) {
    return Array.isArray(params.args)
      ? this.findManyById({ ...params, args: { id: params.args } })
      : this.findById(params);
  }

  findAll ({ args, databases, models, json }) {
    const db = databases.sequelize;
    const TABLE = this.table;

    return promise((resolve, reject) => {
      Model({
        db,
        fields: json[TABLE].schema,
        table: TABLE
      })
        .then(sql => sql.findAll())
        .then(response => response.map(item => item.dataValues))
        .then(data => resolve(data))
        .catch(error => reject(error));
    });
  }

  findById ({ query, args, databases, models }) {
    const db = databases.sequelize;
    let obj = args || query;
    const TABLE = this.table;
  }

  findManyById ({ query, args, databases, models }) {
    const db = databases.sequelize;
    let obj = args || query;
    const TABLE = this.table;
    const ids = obj.id.map(id => ({ id }));
  }
}

export class SequelizeMutation {
  constructor () {
    autobind(this);
  }

  create ({ args, databases, models }) {
    const db = databases.sequelize;
    const TABLE = this.table;
  }

  remove ({ args, databases, models }) {
    const db = databases.sequelize;
    const id = args.id;
    const TABLE = this.table;
  }

  update ({ args, databases, models }) {
    const db = databases.sequelize;
    const id = args.id;
    const TABLE = this.table;
  }

  // createMany
  // deleteMany
  // removeMany
  // updateMany
}
```

**Comment by otissv** [comment]
Hi @jamsheer-thottathil 

Support for PostgreSQL, MySQL, SQLite and MSSQL for has been added through sequelizejs. Also, I added auto-generating models for basic models.

 See [graphql-guru-sequelize](https://github.com/otissv/graphql-guru-sequelize ) for instructions.
